### ISSUE TITLE
Solarized 8

### ISSUE THREAD

**Issue by lifepillar** [dshil/dotfiles#47]
I have stumbled upon https://github.com/dshil/dotfiles/commit/15d611277f77382bfd52e5969920b15d951ab477.

You may want to know that my *maintained* fork [Solarized 8](https://github.com/lifepillar/vim-solarized8) is immune to the issue by default.

**Comment by lifepillar** [comment]
Btw, Gruvbox has the same issue as Solarized, IIRC. You may want to check my [Gruvbox 8](https://github.com/lifepillar/vim-gruvbox8) instead.

**Comment by dshil** [comment]
Hi @lifepillar, I've completely removed the gruvbox and solarized usage. I'm pretty happy with the existing colorscheme.

Thanks for your work! I'll close the issue.
